name: dsplat
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_kmp_llvm
- absl-py=2.1.0=pyhd8ed1ab_0
- alsa-lib=1.2.13=hb9d3cd8_0
- anyio=4.4.0=pyhd8ed1ab_0
- aom=3.9.1=hac33072_0
- argon2-cffi=23.1.0=pyhd8ed1ab_0
- argon2-cffi-bindings=21.2.0=py311h459d7ec_4
- arrow=1.3.0=pyhd8ed1ab_0
- asttokens=2.4.0=pyhd8ed1ab_0
- async-lru=2.0.4=pyhd8ed1ab_0
- attr=2.5.1=h166bdaf_1
- attrs=23.2.0=pyh71513ae_0
- babel=2.14.0=pyhd8ed1ab_0
- backcall=0.2.0=pyh9f0ad1d_0
- backports=1.0=pyhd8ed1ab_3
- backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
- bash=5.2.37=h4be8908_0
- beautifulsoup4=4.12.3=pyha770c72_0
- binutils_impl_linux-64=2.40=hf600244_0
- binutils_linux-64=2.40=hbdbef99_2
- bleach=6.1.0=pyhd8ed1ab_0
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py311hb755f60_1
- bzip2=1.0.8=h7f98852_4
- c-ares=1.34.4=hb9d3cd8_0
- ca-certificates=2023.7.22=hbcca054_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cairo=1.18.2=h3394656_1
- cattrs=23.2.3=pyhd8ed1ab_0
- certifi=2023.7.22=pyhd8ed1ab_0
- cffi=1.17.0=py311ha8e6434_0
- cgal=6.0.1=py311hde4539e_0
- cgal-cpp=6.0.1=h6aadc51_0
- charset-normalizer=3.3.0=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_0
- comm=0.1.4=pyhd8ed1ab_0
- contourpy=1.1.1=py311h9547e67_1
- cuda-version=11.8=h70ddcb2_2
- cudatoolkit=11.8.0=h4ba93d1_12
- cudnn=9.3.0.75=hc149ed2_0
- cupy=13.3.0=py311h878bca4_2
- cupy-core=13.3.0=py311h7b40851_2
- cusparselt=0.5.0.1=hd5ab71f_1
- cutensor=2.0.2.5=hee583db_0
- cycler=0.12.1=pyhd8ed1ab_0
- cyrus-sasl=2.1.27=h54b06d7_7
- dav1d=1.2.1=hd590300_0
- dbus=1.13.6=h5008d03_3
- debugpy=1.8.0=py311hb755f60_1
- decorator=5.1.1=pyhd8ed1ab_0
- defusedxml=0.7.1=pyhd8ed1ab_0
- docstring-to-markdown=0.14=pyhd8ed1ab_0
- double-conversion=3.3.0=h59595ed_0
- eigen=3.4.0=h00ab1b0_0
- entrypoints=0.4=pyhd8ed1ab_0
- exceptiongroup=1.1.3=pyhd8ed1ab_0
- executing=1.2.0=pyhd8ed1ab_0
- expat=2.6.4=h5888daf_0
- faiss=1.9.0=py311cuda118haa09c8f_0_cuda
- faiss-gpu=1.9.0=h418687c_0
- fastrlock=0.8.2=py311hb755f60_2
- ffmpeg=7.1.0=gpl_h099772d_709
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.15.0=h7e30c49_1
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.43.1=py311h459d7ec_0
- fqdn=1.5.1=pyhd8ed1ab_0
- freeglut=3.2.2=ha6d2627_3
- freetype=2.12.1=h267a509_2
- fribidi=1.0.10=h36c2ea0_0
- gcc_impl_linux-64=13.2.0=h338b0a0_3
- gcc_linux-64=13.2.0=h112eaf3_2
- gdk-pixbuf=2.42.12=hb9ae30d_0
- gettext=0.21.1=h27087fc_0
- glib=2.82.2=h44428e9_0
- glib-tools=2.82.2=h4833e2c_0
- gmp=6.3.0=h59595ed_0
- gnutls=3.7.9=hb077bed_0
- graphite2=1.3.13=h58526e2_1001
- grpcio=1.67.1=py311h9789449_2
- gst-plugins-base=1.24.7=h0a52356_0
- gstreamer=1.24.7=hf3bb09a_0
- gxx_impl_linux-64=13.2.0=h338b0a0_3
- gxx_linux-64=13.2.0=hc53e3bf_2
- h11=0.14.0=pyhd8ed1ab_0
- h2=4.1.0=pyhd8ed1ab_0
- harfbuzz=10.4.0=h76408a6_0
- hdf5=1.14.4=nompi_h2d575fe_103
- hpack=4.0.0=pyh9f0ad1d_0
- httpcore=1.0.5=pyhd8ed1ab_0
- httpx=0.27.2=pyhd8ed1ab_0
- hyperframe=6.0.1=pyhd8ed1ab_0
- icecream=2.1.3=pyhd8ed1ab_0
- icu=75.1=he02047a_0
- idna=3.4=pyhd8ed1ab_0
- imageio=2.31.5=pyh8c1a49c_0
- imath=3.1.12=h7955e40_0
- importlib-metadata=6.8.0=pyha770c72_0
- importlib_metadata=6.8.0=hd8ed1ab_0
- importlib_resources=6.4.4=pyhd8ed1ab_0
- ipykernel=6.26.0=pyhf8b6a83_0
- ipympl=0.9.3=pyhd8ed1ab_0
- ipython=8.16.1=pyh0d859eb_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=8.1.1=pyhd8ed1ab_0
- isoduration=20.11.0=pyhd8ed1ab_0
- jasper=4.2.4=h536e39c_0
- jax=0.4.34=pyhd8ed1ab_0
- jaxlib=0.4.34=cpu_py311hd2c3fb4_2
- jedi=0.19.1=pyhd8ed1ab_0
- jedi-language-server=0.41.2=pyhd8ed1ab_0
- jinja2=3.1.2=pyhd8ed1ab_1
- json5=0.9.25=pyhd8ed1ab_0
- jsonpointer=3.0.0=py311h38be061_0
- jsonschema=4.23.0=pyhd8ed1ab_0
- jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
- jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
- jupyter=1.1.1=pyhd8ed1ab_1
- jupyter-lsp=2.2.5=pyhd8ed1ab_0
- jupyter_client=8.6.2=pyhd8ed1ab_0
- jupyter_console=6.6.3=pyhd8ed1ab_1
- jupyter_core=5.4.0=py311h38be061_0
- jupyter_events=0.10.0=pyhd8ed1ab_0
- jupyter_server=2.14.2=pyhd8ed1ab_0
- jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
- jupyterlab=4.3.6=pyhd8ed1ab_0
- jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
- jupyterlab_server=2.27.3=pyhd8ed1ab_0
- jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
- kernel-headers_linux-64=3.10.0=he073ed8_18
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.5=py311h9547e67_1
- krb5=1.21.3=h659f571_0
- lame=3.100=h166bdaf_1003
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.40=h41732ed_0
- lerc=4.0.0=h27087fc_0
- level-zero=1.21.2=h84d6215_0
- libabseil=20240722.0=cxx17_h5888daf_1
- libaec=1.1.3=h59595ed_0
- libasprintf=0.22.5=he8f35ee_3
- libass=0.17.3=hba53ac1_1
- libblas=3.9.0=16_linux64_mkl
- libboost=1.86.0=hb8260a3_2
- libboost-devel=1.86.0=h1a2810e_2
- libboost-headers=1.86.0=ha770c72_2
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcap=2.69=h0f662aa_0
- libcblas=3.9.0=16_linux64_mkl
- libclang=20.1.1=default_hb5137d0_0
- libclang-cpp15=15.0.7=default_h127d8a8_5
- libclang-cpp19.1=19.1.7=default_hb5137d0_2
- libclang13=20.1.1=default_h9c6a7e4_0
- libcups=2.3.3=h4637d8d_4
- libcurl=8.10.1=hbbe4b11_0
- libdeflate=1.22=hb9d3cd8_0
- libdrm=2.4.124=hb9d3cd8_0
- libedit=3.1.20191231=he28a2e2_2
- libegl=1.7.0=ha4b6fd6_1
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.6.4=h5888daf_0
- libfaiss=1.9.0=cuda118hf323835_0_cuda
- libffi=3.4.2=h7f98852_5
- libflac=1.4.3=h59595ed_0
- libgcc=14.2.0=h77fa898_1
- libgcc-devel_linux-64=13.2.0=ha9c7c90_103
- libgcc-ng=14.2.0=h69a702a_1
- libgcrypt=1.11.0=h4ab18f5_1
- libgettextpo=0.22.5=he02047a_3
- libgfortran=14.2.0=h69a702a_1
- libgfortran-ng=14.2.0=h69a702a_1
- libgfortran5=14.2.0=hd5240d6_1
- libgl=1.7.0=ha4b6fd6_1
- libglib=2.82.2=h2ff4ddf_0
- libglu=9.0.0=ha6d2627_1004
- libglvnd=1.7.0=ha4b6fd6_1
- libglx=1.7.0=ha4b6fd6_1
- libgomp=14.2.0=h77fa898_1
- libgpg-error=1.50=h4f305b6_0
- libgrpc=1.67.1=h25350d4_2
- libhwloc=2.11.1=default_hecaa2ac_1000
- libiconv=1.18=h4ce23a2_1
- libidn2=2.3.4=h166bdaf_0
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=16_linux64_mkl
- liblapacke=3.9.0=16_linux64_mkl
- libllvm15=15.0.7=hb3ce162_4
- libllvm19=19.1.7=ha7bfdaf_1
- libllvm20=20.1.1=ha7bfdaf_0
- liblzma=5.6.4=hb9d3cd8_0
- libnghttp2=1.64.0=h161d5f1_0
- libnsl=2.0.1=hd590300_0
- libntlm=1.8=hb9d3cd8_0
- libogg=1.3.5=h4ab18f5_0
- libopenblas=0.3.28=pthreads_h94d23a6_1
- libopencv=4.10.0=qt6_py311h023d011_615
- libopenvino=2024.6.0=hac27bb2_3
- libopenvino-auto-batch-plugin=2024.6.0=h4d9b6c2_3
- libopenvino-auto-plugin=2024.6.0=h4d9b6c2_3
- libopenvino-hetero-plugin=2024.6.0=h3f63f65_3
- libopenvino-intel-cpu-plugin=2024.6.0=hac27bb2_3
- libopenvino-intel-gpu-plugin=2024.6.0=hac27bb2_3
- libopenvino-intel-npu-plugin=2024.6.0=hac27bb2_3
- libopenvino-ir-frontend=2024.6.0=h3f63f65_3
- libopenvino-onnx-frontend=2024.6.0=h6363af5_3
- libopenvino-paddle-frontend=2024.6.0=h6363af5_3
- libopenvino-pytorch-frontend=2024.6.0=h5888daf_3
- libopenvino-tensorflow-frontend=2024.6.0=h630ec5c_3
- libopenvino-tensorflow-lite-frontend=2024.6.0=h5888daf_3
- libopus=1.3.1=h7f98852_1
- libpciaccess=0.18=hd590300_0
- libpng=1.6.44=hadc24fc_0
- libpq=17.4=h27ae623_0
- libprotobuf=5.28.3=h6128344_1
- libre2-11=2024.07.02=hbbce691_1
- librsvg=2.58.4=h49af25d_2
- libsanitizer=13.2.0=h7e041cc_3
- libsndfile=1.2.2=hc60ed4a_1
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.49.1=hee588c1_2
- libssh2=1.11.0=h0841786_0
- libstdcxx=14.2.0=hc0a3c3a_1
- libstdcxx-devel_linux-64=13.2.0=ha9c7c90_103
- libstdcxx-ng=13.2.0=h7e041cc_2
- libsystemd0=256.7=h2774228_1
- libtasn1=4.19.0=h166bdaf_0
- libtiff=4.7.0=he137b08_1
- libunistring=0.9.10=h7f98852_0
- libuuid=2.38.1=h0b41bf4_0
- libva=2.22.0=h8a09558_1
- libvorbis=1.3.7=h9c3ff4c_0
- libvpx=1.14.1=hac33072_0
- libwebp-base=1.5.0=h851e524_0
- libxcb=1.17.0=h8a09558_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.7.0=h2c5496b_1
- libxml2=2.13.6=h8d12d68_0
- libzlib=1.3.1=hb9d3cd8_2
- llvm-openmp=15.0.7=h0cdce71_0
- lsprotocol=2023.0.1=pyhd8ed1ab_0
- lz4-c=1.9.4=hcb278e6_0
- markdown=3.6=pyhd8ed1ab_0
- markupsafe=2.1.3=py311h459d7ec_1
- matplotlib=3.8.0=py311h38be061_2
- matplotlib-base=3.8.0=py311h54ef318_2
- matplotlib-inline=0.1.6=pyhd8ed1ab_0
- mistune=3.0.2=pyhd8ed1ab_0
- mkl=2022.1.0=h84fe81f_915
- ml_dtypes=0.3.1=py311h320fe9a_2
- mpfr=4.2.1=h90cbb55_3
- mpg123=1.32.3=h59595ed_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=9.0.1=h266115a_2
- mysql-libs=9.0.1=he0572af_2
- nbclient=0.10.0=pyhd8ed1ab_0
- nbconvert-core=7.16.4=pyhd8ed1ab_1
- nbformat=5.10.4=pyhd8ed1ab_0
- nccl=2.23.4.1=h03a54cd_2
- ncurses=6.4=hcb278e6_0
- nest-asyncio=1.5.8=pyhd8ed1ab_0
- nettle=3.9.1=h7ab15ed_0
- ninja=1.13.1=h171cf75_0
- notebook=7.3.3=pyhd8ed1ab_0
- notebook-shim=0.2.4=pyhd8ed1ab_0
- nspr=4.36=h5888daf_0
- nss=3.108=h159eef7_0
- numcpp=2.12.1=had84ea8_0
- numpy=1.26.0=py311h64a7726_0
- ocl-icd=2.3.2=hd590300_1
- ocl-icd-system=1.0.0=1
- openblas=0.3.28=pthreads_h6ec200e_1
- opencv=4.10.0=qt6_py311h216f146_615
- openexr=3.3.2=hccdc605_0
- openh264=2.5.0=hf92e6e3_0
- openjpeg=2.5.2=h488ebb8_0
- openldap=2.6.9=he970967_0
- openssl=3.4.1=h7b32b05_0
- opt-einsum=3.3.0=hd8ed1ab_2
- opt_einsum=3.3.0=pyhc1e730c_2
- overrides=7.7.0=pyhd8ed1ab_0
- p11-kit=0.24.1=hc5aa10d_0
- packaging=23.2=pyhd8ed1ab_0
- pandas=2.2.2=py311h320fe9a_0
- pandocfilters=1.5.0=pyhd8ed1ab_0
- pango=1.54.0=h861ebed_4
- parso=0.8.3=pyhd8ed1ab_0
- pcre2=10.44=hba22ea6_2
- pexpect=4.8.0=pyh1a96a4e_2
- pickleshare=0.7.5=py_1003
- pillow=11.0.0=py311h49e9ac3_0
- pip=23.3=pyhd8ed1ab_0
- pixman=0.44.2=h29eaf8c_0
- pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
- platformdirs=3.11.0=pyhd8ed1ab_0
- ply=3.11=py_1
- plyfile=1.0.1=pyhd8ed1ab_0
- prometheus_client=0.20.0=pyhd8ed1ab_0
- prompt-toolkit=3.0.39=pyha770c72_0
- prompt_toolkit=3.0.39=hd8ed1ab_0
- protobuf=5.28.3=py311hfdbb021_0
- psutil=5.9.5=py311h459d7ec_1
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pugixml=1.14=h59595ed_0
- pulseaudio-client=17.0=hb77b528_0
- pure_eval=0.2.2=pyhd8ed1ab_0
- py-opencv=4.10.0=qt6_py311hd8ed033_615
- pybind11=2.12.0=py311h9547e67_0
- pybind11-global=2.12.0=py311h9547e67_0
- pycparser=2.22=pyhd8ed1ab_0
- pygls=1.3.0=pyhd8ed1ab_0
- pygments=2.16.1=pyhd8ed1ab_0
- pyparsing=3.1.1=pyhd8ed1ab_0
- pyqt=5.15.9=py311hf0fb5b6_5
- pyqt5-sip=12.12.2=py311hb755f60_5
- pyquaternion=0.9.9=pyhd8ed1ab_1
- pysocks=1.7.1=pyha2e5f31_6
- python=3.11.8=hab00c5b_0_cpython
- python-dateutil=2.8.2=pyhd8ed1ab_0
- python-fastjsonschema=2.20.0=pyhd8ed1ab_0
- python-json-logger=2.0.7=pyhd8ed1ab_0
- python-tzdata=2024.1=pyhd8ed1ab_0
- python_abi=3.11=4_cp311
- pytz=2024.1=pyhd8ed1ab_0
- pyyaml=6.0.1=py311h459d7ec_1
- pyzmq=25.1.1=py311h34ded2d_2
- qt-main=5.15.15=hc3cb62f_2
- qt6-main=6.8.1=h588cce1_2
- re2=2024.07.02=h77b4e00_1
- readline=8.2=h8228510_1
- referencing=0.35.1=pyhd8ed1ab_0
- requests=2.31.0=pyhd8ed1ab_0
- rfc3339-validator=0.1.4=pyhd8ed1ab_0
- rfc3986-validator=0.1.1=pyh9f0ad1d_0
- rpds-py=0.20.0=py311hb3a8bbb_0
- scipy
- send2trash=1.8.3=pyh0d859eb_0
- setuptools=68.2.2=pyhd8ed1ab_0
- sip=6.7.12=py311hb755f60_0
- six=1.16.0=pyh6c4a22f_0
- snappy=1.2.1=ha2e4443_0
- sniffio=1.3.1=pyhd8ed1ab_0
- soupsieve=2.5=pyhd8ed1ab_1
- stack_data=0.6.2=pyhd8ed1ab_0
- svt-av1=2.3.0=h5888daf_0
- sysroot_linux-64=2.17=h4a8ded7_18
- tbb=2021.13.0=h84d6215_0
- tbb-devel=2021.13.0=h94b29a5_0
- tensorboard=2.18.0=pyhd8ed1ab_0
- tensorboard-data-server=0.7.0=py311h63ff55d_1
- terminado=0.18.1=pyh0d859eb_0
- tinycss2=1.3.0=pyhd8ed1ab_0
- tk=8.6.13=noxft_h4845f30_101
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.1=pyhd8ed1ab_0
- tornado=6.3.3=py311h459d7ec_1
- tqdm=4.66.1=pyhd8ed1ab_0
- traitlets=5.12.0=pyhd8ed1ab_0
- types-python-dateutil=2.9.0.20240821=pyhd8ed1ab_0
- typing-extensions=4.8.0=hd8ed1ab_0
- typing_extensions=4.8.0=pyha770c72_0
- typing_utils=0.1.0=pyhd8ed1ab_0
- tzdata=2023c=h71feb2d_0
- uri-template=1.3.0=pyhd8ed1ab_0
- urllib3=2.0.7=pyhd8ed1ab_0
- wayland=1.23.1=h3e06ad9_0
- wayland-protocols=1.37=hd8ed1ab_0
- wcwidth=0.2.8=pyhd8ed1ab_0
- webcolors=24.8.0=pyhd8ed1ab_0
- webencodings=0.5.1=pyhd8ed1ab_2
- websocket-client=1.8.0=pyhd8ed1ab_0
- werkzeug=3.0.1=pyhd8ed1ab_0
- wheel=0.41.2=pyhd8ed1ab_0
- widgetsnbextension=4.0.9=pyhd8ed1ab_0
- x264=1!164.3095=h166bdaf_2
- x265=3.5=h924138e_3
- xcb-util=0.4.1=hb711507_2
- xcb-util-cursor=0.1.5=hb9d3cd8_0
- xcb-util-image=0.4.0=hb711507_2
- xcb-util-keysyms=0.4.1=hb711507_0
- xcb-util-renderutil=0.3.10=hb711507_0
- xcb-util-wm=0.4.2=hb711507_0
- xkeyboard-config=2.40=hd590300_0
- xorg-fixesproto=5.0=h7f98852_1002
- xorg-inputproto=2.3.2=h7f98852_1002
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.1.2=hb9d3cd8_0
- xorg-libsm=1.2.6=he73a12e_0
- xorg-libx11=1.8.10=h4f16b4b_0
- xorg-libxau=1.0.11=hd590300_0
- xorg-libxcomposite=0.4.6=hb9d3cd8_2
- xorg-libxcursor=1.2.3=hb9d3cd8_0
- xorg-libxdamage=1.1.6=hb9d3cd8_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.6=hb9d3cd8_0
- xorg-libxfixes=6.0.1=hb9d3cd8_0
- xorg-libxi=1.8.2=hb9d3cd8_0
- xorg-libxrandr=1.5.4=hb9d3cd8_0
- xorg-libxrender=0.9.11=hd590300_0
- xorg-libxtst=1.2.5=hb9d3cd8_1
- xorg-libxxf86vm=1.1.6=hb9d3cd8_0
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
- xorg-xorgproto=2024.1=hb9d3cd8_1
- xz
- yaml=0.2.5=h7f98852_2
- zeromq=4.3.5=h59595ed_0
- zipp=3.17.0=pyhd8ed1ab_0
- zlib=1.3.1=hb9d3cd8_2
- zstd=1.5.7=hb8e6e7a_2

